
Organizations:
  - &KaizenOrdererOrg
    Name: KaizenOrdererOrg
    ID: KaizenOrdererMSP
    MSPDIR: crypto-config/ordererOrganizations/kaizen-solutions.net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('KaizenOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('KaizenOrdererMSP.member', 'LabOrgMSP.admin')"
      Admins:
        Type: Signature
        Rule: "OR('KaizenOrdererMSP.admin')"

  - &LabOrg
    Name: LabOrgMSP
    ID: LabOrgMSP
    MSPDIR: crypto-config/peerOrganizations/lab.kaizen-solutions.net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('LabOrgMSP.admin', 'LabOrgMSP.peer', 'LabOrgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('LabOrgMSP.admin', 'LabOrgMSP.peer')"
      Admins:
        Type: Signature
        Rule: "OR('LabOrgMSP.admin')"
    AnchorPeers:
      - Host: peer0.lab.kaizen-solutions.net
        Port: 7051
      - Host: peer1.lab.kaizen-solutions.net
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: false
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.kaizen-solutions.net:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  KaizenOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *KaizenOrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      KaizenConsortium:
        Organizations:
          - *LabOrg
  KaizenChannel:
    Consortium: KaizenConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *LabOrg
      Capabilities:
        <<: *ApplicationCapabilities
