OrdererOrgs:
  - Name: KaizenOrderer
    Domain: kaizen-solutions.net
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: LabOrg
    Domain: lab.kaizen-solutions.net
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
    Users:
      Count: 1
