version: '3.5'

services:
  lab-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    container_name: ca_peerLabOrg
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-laborg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.lab.kaizen-solutions.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$FABRIC_CA_SERVER_TLS_KEYFILE
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.lab.kaizen-solutions.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$FABRIC_CA_SERVER_TLS_KEYFILE -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - chocoblastchain

  orderer.kaizen-solutions.net:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    container_name: orderer.kaizen-solutions.net
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=KaizenOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/kaizen-solutions.net/orderers/orderer.kaizen-solutions.net/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/kaizen-solutions.net/orderers/orderer.kaizen-solutions.net/tls/:/var/hyperledger/orderer/tls
#      - orderer.kaizen-solutions.net:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - chocoblastchain

  peer0.lab.kaizen-solutions.net:
    container_name: peer0.lab.kaizen-solutions.net
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=chocoblastchain
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.lab.kaizen-solutions.net
      - CORE_PEER_ADDRESS=peer0.lab.kaizen-solutions.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lab.kaizen-solutions.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lab.kaizen-solutions.net:7051
      - CORE_PEER_LOCALMSPID=LabOrgMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=$CHAINCODE_DEV
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/peers/peer0.lab.kaizen-solutions.net/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/peers/peer0.lab.kaizen-solutions.net/tls:/etc/hyperledger/fabric/tls
      - peer0.lab.kaizen-solutions.net:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060
    networks:
      - chocoblastchain

  peer1.lab.kaizen-solutions.net:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    container_name: peer1.lab.kaizen-solutions.net
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=chocoblastchain
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.lab.kaizen-solutions.net
      - CORE_PEER_ADDRESS=peer1.lab.kaizen-solutions.net:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.lab.kaizen-solutions.net:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.lab.kaizen-solutions.net:8051
      - CORE_PEER_LOCALMSPID=LabOrgMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=$CHAINCODE_DEV
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/peers/peer1.lab.kaizen-solutions.net/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/peers/peer1.lab.kaizen-solutions.net/tls:/etc/hyperledger/fabric/tls
      - peer1.lab.kaizen-solutions.net:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060
    networks:
      - chocoblastchain

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.lab.kaizen-solutions.net:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './init_channel.sh'
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/lab.kaizen-solutions.net/peers/peer0.lab.kaizen-solutions.net/msp:/etc/hyperledger/msp
      - ./../chaincode:/opt/gopath/src/chaincodedev/chaincode
      - ./:/opt/gopath/src/chaincodedev/
    depends_on:
      - orderer.kaizen-solutions.net
      - peer0.lab.kaizen-solutions.net
    networks:
      - chocoblastchain

networks:
  chocoblastchain:

volumes:
  orderer.kaizen-solutions.net:
  peer0.lab.kaizen-solutions.net:
  peer1.lab.kaizen-solutions.net:
